auth/urls.py
from django.urls import path
from auth import views

urlpatterns = [
    # We can use this name in another app
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.Logout.as_view(), name='logout')
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('checkout/', views.checkout, name='checkout'),
    path('cart/', views.cart, name='cart'),
    path('display/', views.displayTemplates, name='display'),

    path('api/add-remove-cart', views.addRemoveCart),
    path('api/update-product-quantity', views.updateProductQuantity)
]

stylestore/urls.py
from django.contrib import admin
from django.urls import path, include 

# from django.http import HttpResponse
# from . import errorhandlers
# from django.contrib.auth.decorators import login_required
# from auth import views as auth_views

urlpatterns = [
    path('', include('main.urls')),
    path('auth/', include('auth.urls')),
    # path('admin/login/', auth_views.login),
    path('admin/', admin.site.urls),
]

handler404 = 'stylestore.errorhandlers.handler404'

# lambda request: admin.site.urls if request.user.is_superuser else HttpResponse(status=404)
# errorhandlers.handler404(request, None)

# https://pypi.org/project/django-decorator-include/

main/models.py
from django.db import models

from django.conf import settings

# Create your models here.


class Address(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)

    line_1 = models.CharField(max_length = 50)
    line_2 = models.CharField(max_length = 50)
    city = models.CharField(max_length = 20)
    state = models.CharField(max_length = 20)
    country = models.CharField(max_length = 20)
    pin_code = models.CharField(max_length = 10)

    is_shipping = models.BooleanField(default = False)
    is_billing = models.BooleanField(default = False)

    def __str__(self):
        return self.line_1
    
    class Meta:
        verbose_name_plural = "addresses"

class Coupon(models.Model):
    name = models.CharField(max_length = 6)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    is_valid = models.BooleanField(default = True)
    discount_percentage = models.FloatField()
    
    class Meta:
        verbose_name_plural = "coupons"

class Styles(models.Model):
    name = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    image_model = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "styles"

class Templates(models.Model):
    name = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    unit_price = models.FloatField()

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "templates"

class CustomUser(models.Model):
    username = models.CharField(max_length=150, unique = True)
    phone_number = models.CharField(max_length = 15, null = True)
    GENDERS = (
        ('f', 'Female'),
        ('m', 'Male'),
        ('u', 'Undisclosed'),
    )
    gender = models.CharField(max_length = 1, choices = GENDERS, null = True)

    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name_plural = "CustomUsers"

class Order(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)

    coupon_used = models.ForeignKey('Coupon', on_delete=models.CASCADE)
    discount = models.FloatField()
    PAYMENT_TYPES = (
        ('c', 'Cash on delivery'),
        ('d', 'Debit Card'),
        ('p', 'PayTM'),
    )
    payment_type = models.CharField(max_length = 1, choices = PAYMENT_TYPES)
    payment_status = models.BooleanField()

    ordered_at = models.DateTimeField()
    expected_delivery = models.DateTimeField()
    delivered_at = models.DateTimeField()

    shipping_address = models.ForeignKey('Address', on_delete=models.CASCADE, related_name = 'shipping_address_set')
    billing_address = models.ForeignKey('Address', on_delete=models.CASCADE, related_name = 'billing_address_set')
    class Meta:
        verbose_name_plural = "orders"

class CompleteDesign(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    is_public = models.BooleanField(default = True)

    content_image = models.URLField()
    style = models.ForeignKey('Styles', on_delete=models.CASCADE)
    result_design = models.URLField()

    # storing python list as a string
    styled_templates = models.TextField()
    
    class Meta:
        verbose_name_plural = "CompleteDesigns"

class Cart(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    is_purchased = models.BooleanField()
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null = True, blank = True)

    complete_design = models.ForeignKey('CompleteDesign', on_delete=models.CASCADE)

    template = models.ForeignKey('Templates', on_delete=models.CASCADE)
    styled_template_url = models.URLField()

    quantity = models.IntegerField()
    unit_price = models.FloatField()

    added_at = models.DateTimeField()
    last_updated_at = models.DateTimeField()
    
    class Meta:
        verbose_name_plural = "cart"

main/forms.py
from django import forms

# Create your forms here.

from main import models

class CreateStyledImageForm(forms.Form):
    content_image = forms.FileField()
    style = forms.CharField()

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.utils import timezone
import os
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from keras.preprocessing.image import save_img
import numpy as np
from django.contrib.auth.decorators import login_required
tf.compat.v1.enable_eager_execution()

from django.conf import settings

from main import models as main_models
from main import forms as main_forms

import cloudinary
import requests
import io
from PIL import Image

nav_cart_limit = 3
cloudinary.config( 
    cloud_name = os.getenv("CLOUD_NAME"),
    api_key = os.getenv("API_KEY"),
    api_secret = os.getenv("API_SECRET")
)

def load_img(path_to_img):
    # img = tf.io.read_file(path_to_img)
    img = requests.get(path_to_img).content
    img = tf.image.decode_jpeg(img, channels=3)
    # the following line will convert the image to float value ie between 0 and 1
    img = tf.image.convert_image_dtype(img, tf.float32)
    # the following line will resize the image to 256,256
    img = tf.image.resize(img, (256, 256))
    # the following line will add a new axis to the image
    img = img[tf.newaxis, :]
    return img

def tensor_to_image(tensor):
    tensor = tensor*255
    tensor = np.array(tensor.numpy(), dtype=np.uint8)
    if np.ndim(tensor)>3:
        assert tensor.shape[0] == 1
        tensor = tensor[0]
    return tensor

# from main.functions.functions import handle_uploaded_file
# Create your views here.
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), padding='same', input_shape=(256, 256, 3)))
model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
									beta_initializer='zeros', gamma_initializer='ones',
									moving_mean_initializer='zeros',
									moving_variance_initializer='ones'))  # , beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (3, 3), padding='same'))
model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
									beta_initializer='zeros', gamma_initializer='ones',
									moving_mean_initializer='zeros',
									moving_variance_initializer='ones'))  # , beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Conv2D(128, (3, 3), padding='same'))
model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
									beta_initializer='zeros', gamma_initializer='ones',
									moving_mean_initializer='zeros',
									moving_variance_initializer='ones'))  # , beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
# model.add(layers.Conv2D(256, (3, 3), padding='same'))
# model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True, beta_initializer='zeros', gamma_initializer='ones', moving_mean_initializer='zeros', moving_variance_initializer='ones'))#, beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
# model.add(Activation('relu'))
# model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Conv2D(256, (3, 3), activation='relu', padding='same'))
model.add(layers.Conv2D(256, (3, 3), padding='same'))
model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
									beta_initializer='zeros', gamma_initializer='ones',
									moving_mean_initializer='zeros',
									moving_variance_initializer='ones'))  # , beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
model.add(layers.Activation('relu'))
model.add(layers.Conv2D(256, (3, 3), activation='relu', padding='same'))
model.add(layers.Conv2DTranspose(128, (3, 3), strides=(2, 2), padding='same'))
model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
									beta_initializer='zeros', gamma_initializer='ones',
									moving_mean_initializer='zeros',
									moving_variance_initializer='ones'))  # , beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
model.add(layers.Activation('relu'))
model.add(layers.Conv2DTranspose(64, (3, 3), strides=(2, 2), padding='same'))
model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
									beta_initializer='zeros', gamma_initializer='ones',
									moving_mean_initializer='zeros',
									moving_variance_initializer='ones'))  # , beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
model.add(layers.Activation('relu'))
model.add(layers.Conv2DTranspose(32, (3, 3), strides=(2, 2), padding='same'))
model.add(layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
									beta_initializer='zeros', gamma_initializer='ones',
									moving_mean_initializer='zeros',
									moving_variance_initializer='ones'))  # , beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
model.add(layers.Activation('relu'))
model.add(layers.Conv2D(3, (3, 3), activation='tanh', padding='same'))

def uploadImage(image, path):
    # https://cloudinary.com/documentation/django_integration
    # cloudinary.uploader.upload("dog.mp4", 
    # folder = "my_folder/my_sub_folder/", 
    # public_id = "my_dog",
    # overwrite = true, 
    # notification_url = "https://mysite.example.com/notify_endpoint", 
    # resource_type = "video")
    
    # upload image to cloud
    # cloudinary.uploader.upload(request.FILES['file'])
    print("cloudinary upload 1")
    uploaded_image = cloudinary.uploader.upload(image,
        folder = path,
        overwrite = True,
        resource_type = "image"
    )
    print("cloudinary upload 2")
    image_url = uploaded_image["secure_url"]
    # image_url = uploaded_image["url"]
    print(image_url)
    return image_url

def processStyleForm(style_form_json, username):
    style_id = style_form_json['style_id']
    content_image_url = style_form_json['content_image_url']

    temp = main_models.Styles.objects.get(id = style_id)
    # now we have somehow form the final image
    # temp = CompleteShirt.objects.latest('id')
    # model.load_weights(temp.style.image_ckpt.url[1:])

    print("Index Page 1")
    model.load_weights(settings.DATA["STYLES_IMAGE_MODEL"] + temp.image_model)
    print("Index Page 2")

    image = load_img(content_image_url)
    print("Index Page 3")
    image = model(image)
    print("Index Page 4")
    image = (image+1)/2
    print("Index Page 5")
    image = tensor_to_image(image)
    print("Index Page 6")
    # saving result image at result_image_url path
    out_img = Image.fromarray(image).convert('RGB')
    result_design_io = io.BytesIO()
    out_img.save(result_design_io, format='png')
    result_design_io.seek(0)
    result_design_url = uploadImage(result_design_io, settings.DATA["RESULT_IMAGE_CLOUD"])
    # ==================================
    # result_design_url = settings.DATA["RESULT_IMAGE"]
    # save_img(result_design_url, image)
    # result_design_url = "/" + result_design_url
    # os.system("python manage.py collectstatic --no-input")
    print("Index Page 7")

    # os.system(". tf/bin/activate")
    # os.system("python3 fast-style-transfer-master/evaluate.py --checkpoint "+temp.style.image_ckpt.url[1:]+" --in-path "+temp.content.url[1:]+" --out-path media/images/123.jpg")

    styled_templates = {}
    templates = main_models.Templates.objects.all().values()
    for i in templates:
        styled_template_io = io.BytesIO()
        background = Image.open(result_design_io)
        foreground = Image.open(i['image'])
        background.paste(foreground, (0, 0), foreground)
        background.save(styled_template_io, format='png')
        styled_template_io.seek(0)
        styled_template_url = uploadImage(styled_template_io,  settings.DATA["STYLED_TEMPLATE_CLOUD"])

        styled_templates[str(i['id'])] = styled_template_url

    print("Index Page 7")
    custom_user = main_models.CustomUser.objects.filter(username = username).first()
    complete_design = {
        'user_id': custom_user.id,
        'content_image': content_image_url,
        'style_id': style_id,
        'result_design': result_design_url,
        'styled_templates': str(styled_templates)
    }

    complete_design_object = main_models.CompleteDesign.objects.create(**complete_design)
    complete_design['id'] = complete_design_object.id
    complete_design['styled_templates_list'] = styled_templates
    print("Index Page 8")
    return complete_design

def index(request):
    if request.session.get('display_active', False):
        return HttpResponseRedirect('/display/')
    
    if request.session.get('style_form_json', None) and request.user.is_authenticated:
        style_form_json = request.session['style_form_json']
        complete_design = processStyleForm(style_form_json, request.user.get_username())
        request.session['complete_design'] = complete_design
        del request.session['style_form_json']
        return HttpResponseRedirect('/display/')
    
    errors = None
    if request.method == "POST":
        form = main_forms.CreateStyledImageForm(request.POST, request.FILES)
        if form.is_valid():
            content_image_url = uploadImage(form.cleaned_data['content_image'], settings.DATA["CONTENT_IMAGE_CLOUD"])
            style_form_json = {
                "style_id": form.cleaned_data['style'],
                "content_image_url": content_image_url,
            }

templates/main/cart.html
{% extends 'base.html' %}
{% load static %}
{% load custom_template_tags %}
{% block title %}
Cart
{% endblock %}
{% block style %}
    <style>
    .product_image {
        position: absolute;
        z-index: 5;
        display: none;
    }
    </style>
{% endblock %}
{% block content %}
    {% if cart_products %}
    {% csrf_token %}
    <div class="container-fluid">
        <div class="py-5 text-center">
            <button class="btn btn-primary float-right m-1" onclick="saveCart()">Save Cart</button>
            <a href="{% url 'checkout' %}"><button class="btn btn-primary float-right m-1">Checkout <i class="fas fa-long-arrow-alt-right"></i></button></a>
            <h2>Cart</h2>
        </div>

        <table class="table table-hover text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Unit Price</th>
                    <th scope="col">Expected Delivery</th>
                    <th scope="col">Total Price</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for each_product in cart_products %}
                <tr onmouseover="showProductImg(this)" onmouseout="hideProductImg(this)">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        {{each_product.template.name}}
                        <img src="{{each_product.styled_template_url}}" class="product_image">
                    </td>
                    <td>
                        <i class="fas fa-minus-circle decQty" onclick="changeCartQuantity(this, -1)" style="cursor: pointer;"></i>
                        <input type="text" class="cartId" value="{{each_product.id}}" hidden>
                        <input type="text" class="isUpdated" value="0" hidden>
                        <span class="cartQty">{{each_product.quantity}}</span>
                        <i class="fas fa-plus-circle incQty" onclick="changeCartQuantity(this, 1)" style="cursor: pointer;"></i>
                    </td>
                    <td>
                        <i class="fas fa-rupee-sign unit_price">
                        {{each_product.unit_price}}
                        </i>
                    </td>
                    <td>Delivery by Tomorrow</td>
                    <td>
                        <i class="fas fa-rupee-sign total_price">
                        {% multiply each_product.quantity each_product.unit_price %}
                        </i>
                    </td>
                    <td>
                        <i class="fas fa-trash-alt" onclick="deleteProduct(this)" style="cursor: pointer;"></i>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"></td>
                    <td><strong>Total Payable:</strong></td>
                    <td><i class="fas fa-rupee-sign" id="total_payable"> {{total_cart_payable}}</i></td>
                </tr>
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="container-fluid">
        <div class="py-5 text-center">
            <h2>Cart</h2>
            <h3>Cart is empty</h3>
        </div>
    {% endif %}
{% endblock %}

templates/main/display.html
{% extends 'base.html' %}
{% load static %}
{% load custom_template_tags %}
{% block title %}
Book Products
{% endblock %}
{% block style %}
    <style>
    .fa-share {
        cursor: pointer;
    }
    .fa-share:hover {
        color: blue;
    }
    /*
    .styleimage, .templateimage {
        width: 512px;
        height: 512px;
    }
    */
    </style>
{% endblock %}
{% block content %}

    <div class="container-fluid">
        <br>

        <a href="{% url 'display' %}">
            <button type="button" class="btn btn-primary btn-lg float-right">
                Checkout <i class="fas fa-long-arrow-alt-right"></i>
            </button>
        </a>
    
        <br><br><br>
        {% for each_template in templates %}
        <div class="row">
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 styleimage">
                <div style="margin: 0px -15px;" class="" onclick="highlightImage(this)">
                    <img src="{% access styled_templates each_template.id %}" alt="stylized_image" class="templateimage" style="width: 100%">
                    <input type="text" value="{{each_template.id}}" class="templateid" hidden>
                    <input type="text" value="" class="cartid" hidden>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-8 col-lg-6" style="margin: auto;">
                    {% csrf_token %}
                    <i class="fas fa-share float-right" onclick="shareProduct(this)"> Share</i>
                    <h5>Product Description</h5>
                    <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                    when an unknown printer took a galley of type and scrambled it to make a type
                    specimen book.
                    </p>
                    <h5>Price: <i class="fas fa-rupee-sign"> {{each_template.unit_price}}</i></h5>
                    <strong>Available Sizes:</strong>
                    <input type="text" name="productsizes" class="productsizesclass" value="" hidden>
                    <input name="productsizesbutton" class="productsizesclass btn btn-primary btn-sm" type="button" value="L" onclick="selectSize(this)">
                    <input name="productsizesbutton" class="productsizesclass btn btn-primary btn-sm" type="button" value="XL" onclick="selectSize(this)">
                    <input name="productsizesbutton" class="productsizesclass btn btn-primary btn-sm" type="button" value="XXL" onclick="selectSize(this)">
                    <input name="productsizesbutton" class="productsizesclass btn btn-primary btn-sm" type="button" value="XXXL" onclick="selectSize(this)">
                    <br><br>

                    <input type="text" name="products" class="productstatusclass" value="n" hidden>
                    <i class="fas fa-minus-circle decQty" onclick="changeCartQuantity(this, -1)"></i>
                        <span class="cartQty">0</span>
                    <i class="fas fa-plus-circle incQty" onclick="changeCartQuantity(this, 1)"></i>
                    <button type="button" class="btn btn-primary btn-lg" onclick="changeStatusInCart(this)">Add to Cart</button>
            </div>
        </div>
        <br>
        {% endfor %}


        <hr>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'js/display.js' %}"></script>
{% endblock %}

templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-2">Welcome to Stylestore</h1>
            <p class="lead text-right">A wide range of styles and products are available ...</p>
        </div>
    </div>

    {% if styleshirts %}
    <div class="container-fluid">
        <h2 class="display-4">Choose what suits you</h2>
        <form method="POST" enctype="multipart/form-data" action="">
            {% csrf_token %}
            <!-- form.as_p}} -->
            <div class="row">
            {% for styleshirt in styleshirts %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                <div style="margin: 10px 1px; padding: 0px;" class="card border border-info" onclick="highlightImage(this)">
                    <input type="radio" value="{{styleshirt.id}}" name="style" hidden>
                    <img src="{% static styleshirt.image %}" style = "width: 100%; height: 300px;" class="card-img-top img-fluid img-thumbnail" alt="{{styleshirt.name}}">
                    <div class="card-body">
                        <h5 class="card-title">{{styleshirt.name}}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>

            <div class="form-group">
                <label for="id_content_image">Upload Content Image</label>
                <input type="file" class="form-control-file" name="content_image" id="id_content_image">
            </div>

            <button type="submit" class="btn btn-success">SUBMIT</button>
        </form>
    </div>
    <br>
    {% else %}
    No styles present currently
    {% endif %}

    {% if errors %}
    <div class="row justify-content-center">
        <div class="offset-0 col-8 offset-sm-0 col-sm-10 offset-md-0 col-md-10">
        {% for error in errors %}
            <div class="alert alert-danger text-center">{{error}}</div>
        {% endfor %}
        </div>
    </div>
    {% endif %}
    <br>
        <hr>
    </div>
{% endblock %}

templates/main/testing.html
{% extends 'base.html' %}
  
  {% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">SUBMIT</button>
    </form>
    <h2>{{text}}</h2>

  {% endblock %}